services:

  # Database
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: acura_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: acura_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb # set shared memory limit when using docker compose
  adminer:
    image: adminer
    restart: always
    ports:
      - "8086:8080"
  # Orchestration
  # Merge airflow docker-compose at runtime: 
  # docker-compose -f docker-compose.yml -f airflow/airflow-docker-compose.yml up -d